apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment # deployment name
  labels:
    app: ftps # deployment label
spec:
  selector:
    matchLabels:
      app: ftps # match pod label
  template: # pod definition
    metadata:
      labels:
        app: ftps # pod label
    spec:
      containers:
      - name: ftps-container
        image: ftps-image:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps
        - containerPort: 40000
          name: pasv1
        - containerPort: 40001
          name: pasv2
        - containerPort: 40002
          name: pasv3
        - containerPort: 40003
          name: pasv4
        - containerPort: 40004
          name: pasv5
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
      metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps # match deployment and pod labels
  type: LoadBalancer
  ports:
  - protocol: TCP
    name: ftps
    port: 21
    targetPort: 21 # match container port
  - protocol: TCP
    name: pasv1
    port: 40000
    targetPort: 40000
  - protocol: TCP
    name: pasv2
    port: 40001
    targetPort: 40001
  - protocol: TCP
    name: pasv3
    port: 40002
    targetPort: 40002
  - protocol: TCP
    name: pasv4
    port: 40003
    targetPort: 40003
  - protocol: TCP
    name: pasv5
    port: 40004
    targetPort: 40004
