apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment # deployment name
  labels:
    app: grafana # deployment label
spec:
  selector:
    matchLabels:
      app: grafana # match pod label
  template: # pod definition
    metadata:
      labels:
        app: grafana # pod label
    spec:
      containers:
      - name: grafana-container
        image: grafana-image:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
      metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: grafana # match deployment and pod labels
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000 # match container port
