apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 505Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/influxdb-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: influxdb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment # deployment name
  labels:
    app: influxdb # deployment label
spec:
  selector:
    matchLabels:
      app: influxdb # match pod label
  template: # pod definition
    metadata:
      labels:
        app: influxdb # pod label
    spec:
      containers:
      - name: influxdb-container
        image: influxdb-image:1.0
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - 'pgrep telegraf && pgrep influxd'
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /root/.influxdb
        - name: docker-socket-access
          mountPath: /var/run/docker.sock
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pv-claim
      - name: docker-socket-access
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  selector:
    app: influxdb # match deployment and pod labels
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8086
    targetPort: 8086 # match container port
