apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment # deployment name
  labels:
    app: mysql # deployment label
spec:
  selector:
    matchLabels:
      app: mysql # match pod label
  template: # pod definition
    metadata:
      labels:
        app: mysql # pod label
    spec:
      containers:
      - name: mysql-container
        image: mysql-image:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql # match deployment and pod labels
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306 # match container port
