apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 750Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment # deployment name
  labels:
    app: mysql # deployment label
spec:
  selector:
    matchLabels:
      app: mysql # match pod label
  template: # pod definition
    metadata:
      labels:
        app: mysql # pod label
    spec:
      containers:
      - name: mysql-container
        image: mysql-image:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql # match deployment and pod labels
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306 # match container port
