apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment # deployment name
  labels:
    app: phpmyadmin # deployment label
spec:
  selector:
    matchLabels:
      app: phpmyadmin # match pod label
  template: # pod definition
    metadata:
      labels:
        app: phpmyadmin # pod label
    spec:
      containers:
      - name: phpmyadmin-container
        image: phpmyadmin-image:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin # match deployment and pod labels
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000 # match container port
