apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment # deployment name
  labels:
    app: wordpress # deployment label
spec:
  selector:
    matchLabels:
      app: wordpress # match pod label
  template: # pod definition
    metadata:
      labels:
        app: wordpress # pod label
    spec:
      containers:
      - name: wordpress-container
        image: wordpress-image:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
      metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: wordpress # match deployment and pod labels
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050 # match container port
